### ISSUE TITLE
Dependency on CoFHCore?

### ISSUE THREAD

**Issue by Shahelion** [TCLProject/ArsMagica2-5#37]
Why does this mod need CoFHCore? I deliberately do not have any CoFH mods in my pack.

**Comment by AirBurn0** [comment]
> Why does this mod need CoFHCore? I deliberately do not have any CoFH mods in my pack.

Short answer is:
In order to make [RedstoneFluxDrain](https://github.com/TCLProject/ArsMagica2-5/blob/master/src/main/java/am2/spell/components/RedstoneFluxDrain.java) component.

Long answer is:
Cuz someone made hard-dependency on CoFH and **I have literally no idea** why he didn’t make soft-dependency here.
Generally speaking, in modding there are 101 ways to refer to someone else's mod, and this is a bit of a mess, everyone does it differently (for example, see Avaritia 1.7.10 code).
BTW, it’s high time to move CoFH core in soft-dependency, and it seems like in the dev branch it is no longer included in the dependencies, but code still requiresa CoFH core to be (and crashes unless? Didn't tested yet).

If you really need it, I can **try** to make a version of mod without this dependency now, but adding this to the original project will not be so easy, cuz I will need to work it out with the @TCLProject

**Comment by Shahelion** [comment]
It doesn't crash, so much as never reaches the main menu because it stops on the screen telling you it needs any version of CoFHCore.

**Comment by AirBurn0** [comment]
> It doesn't crash, so much as never reaches the main menu because it stops on the screen telling you it needs any version of CoFHCore.

I'm trying to say that there is **[already](https://github.com/TCLProject/ArsMagica2-5/tree/1.7-dev)** a version of the mod that **does not require cofh core and lets you play am2**, but if you strike any tileentity (furnace for example) with [RedstoneFluxDrain](https://github.com/TCLProject/ArsMagica2-5/blob/master/src/main/java/am2/spell/components/RedstoneFluxDrain.java) component, this will happens:
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 08.02.24 13:37
Description: Ticking entity

java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyHandler
	at am2.spell.components.RedstoneFluxDrain.applyEffectBlock(RedstoneFluxDrain.java:34)
	at am2.spell.SpellHelper.applyStageToGround(SpellHelper.java:86)
	at am2.entities.EntitySpellProjectile.HitObject(EntitySpellProjectile.java:460)
	at am2.entities.EntitySpellProjectile.func_70071_h_(EntitySpellProjectile.java:396)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 19 more
```
BTW, 'AM2.5 1.6.5-indev' isn't a release version yet, so your issue is quite appropriate.
### At the moment there is no version of the mod that would work correctly without CoFH Core, but I can try to make one just for you if you ask.

**Comment by Shahelion** [comment]
What about if CoFHCore or the Redstone API isn't detected, it simply doesn't enable the Redstone Flux Drain component and related bits? Would that be doable?

**Comment by AirBurn0** [comment]
> What about if CoFHCore or the Redstone API isn't detected, it simply doesn't enable the Redstone Flux Drain component and related bits? Would that be doable?

That's what I do in [my addon](https://github.com/AirBurn0/am2playground). I don’t understand what the problem is in doing this here, I haven’t tried it. I think that should do.
